name: GraalVM Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Setup GraalVM action
        # You may pin to the exact commit or the version.
        # uses: ayltai/setup-graalvm@eb0db9af1ceb6dadb398847c7e23fc3afa09c0d3
        uses: ayltai/setup-graalvm@master
        with:
          # The JDK version to be installed with GraalVM. E.g. 8, 11. See https://github.com/graalvm/graalvm-ce-builds/releases
          java-version: 11 # optional
          # The version of GraalVM to make available on PATH. E.g. 20.1.0, 19.3.2. See https://github.com/graalvm/graalvm-ce-builds/releases
          # Allineare la versione con pom.xml
          graalvm-version: 20.2.0
          # Install GraalVM Native Image
          native-image: true # optional

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      - name Windows setup
        uses: ilammy/msvc-dev-cmd@v1.5.0
          if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1
          if: ${{ matrix.os == 'windows-latest' }}

      - name: Call maven
        run: mvn -B package --file pom.xml

      - name: Commit files
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "[Automated] Added build files"
